### ISSUE TITLE
Undetected date format

### ISSUE THREAD

**Issue by wezm** [rust-playground/anydate#3]
I'm using `anydate` to try to parse date like things and encountered this case that is not handled. Not sure how hard it would be to add support for:

- Sunday, April 18th, 2021
- Friday, January 8th, 2021
- Tuesday, September 15th, 2020
- Monday, April 6th, 2020
- Friday, March 13th, 2020
- Sunday, June 2nd, 2019
- Wednesday, May 29th, 2019
- Saturday, May 25th, 2019
- Thursday, May 16th, 2019
- Tuesday, May 7th, 2019
- Friday, April 26th, 2019
- Tuesday, April 23rd, 2019
- Wednesday, April 17th, 2019

**Comment by deankarn** [comment]
Sorry for the late response, thanks for the report.

Will try any look into that.
